### ISSUE TITLE
ValueError: expected sequence of length 11 at dim 1 (got 18)

### ISSUE THREAD

**Issue by vnnw** [ctr4si/A-Hierarchical-Latent-Structure-for-Variational-Conversation-Modeling#2]
I cloned the repo to run the train.py on dataset ubuntu,
both commands gave me similar errors as below

```
python train.py --data=ubuntu --model=VHRED --batch_size=40 --word_drop=0.25 --kl_annealing_iter=250000
```
```
python train.py --data=ubuntu --model=VHCR --batch_size=40 --sentence_drop=0.25 --kl_annealing_iter=250000
```
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    solver.train()
  File "/home/user/ML/A-Hierarchical-Latent-Structure-for-Variational-Conversation-Modeling-master/model/utils/time_track.py", line 18, in timed
    result = method(*args, **kwargs)
  File "/home/user/ML/A-Hierarchical-Latent-Structure-for-Variational-Conversation-Modeling-master/model/solver.py", line 466, in train
    sentences = to_var(torch.LongTensor(sentences))
ValueError: expected sequence of length 11 at dim 1 (got 18)
```
But running "python train.py --data=cornell --model=HRED" seems working fine.

I was running with pytorch 0.4.0 which i conda-installed from pytorch channel.

**Comment by jverygood** [comment]
Each sentence has a different dimension， which leads to this error(in LongTensor). I don't know how to solve it too

**Comment by j-min** [comment]
Just found a bug from data preprocessing file and fixed it. => https://github.com/ctr4si/A-Hierarchical-Latent-Structure-for-Variational-Conversation-Modeling/commit/e0d70c5b19ec724dd404ca3c94335417a4722068
Please check it it works now.

**Comment by zhongchaoze** [comment]
咋个搞吗

**Comment by jverygood** [comment]
> 咋个搞吗

作者不是修复了吗
